(()=>{
'use strict';
const EVENTS=[
{date:'9/8(火)〜9/13(日)',time:'時間は公式ページ確認',title:'手織りサークルゆのみ 第17回作品展「小さい手織りとの出会い」',place:'苫小牧市内',tag:'小規模・展示',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/9(水)',time:'10:00〜',title:'ベビープラネタリウム',place:'苫小牧市科学センター',tag:'親子・無料',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/9(水)',time:'14:30〜15:30／16:00〜17:00',title:'プレスクール工作体験「ゆらゆらひかるおばけをつくろう」',place:'苫小牧市科学センター',tag:'未就学児',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/11(金)',time:'16:30〜17:30',title:'星空観望会「天文台で欠けた金星を見よう」',place:'苫小牧市科学センター',tag:'天文・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/12(土)〜9/13(日)',time:'9:30〜20:00（予定）',title:'とまこまいミライフェスト2026',place:'キラキラ公園',tag:'大型イベント',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/12(土)',time:'時間は公式ページ確認',title:'苫小牧バレエ研究所 創立52周年記念公演 TWINS☆★BALLET',place:'苫小牧市民文化ホール ART CUBES',tag:'舞台',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'9/14(月)',time:'時間は公式ページ確認',title:'あなたの街でミーティング（弥生町・錦町・本町・元中野町・旭町地区）',place:'苫小牧市内',tag:'地域・交流',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/16(水)',time:'10:00〜',title:'ベビープラネタリウム',place:'苫小牧市科学センター',tag:'親子・無料',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/16(水)',time:'時間は公式ページ確認',title:'あなたの街でミーティング（植苗地区）',place:'植苗地区',tag:'地域・交流',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/17(木)',time:'時間は公式ページ確認',title:'あなたの街でミーティング（錦岡地区）',place:'錦岡地区',tag:'地域・交流',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/19(土)〜11/23(月・祝)',time:'9:30〜17:00（入館16:30まで）',title:'特別展「棟方志功―北方への祈り」',place:'苫小牧市美術博物館',tag:'展示',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/munakata.html'},
{date:'9/19(土)',time:'11:00〜12:00',title:'棟方志功記念館学芸員による講演会',place:'苫小牧市美術博物館 研修室',tag:'講演・無料',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/munakata.html'},
{date:'9/22(火・祝)',time:'18:00〜18:40',title:'夜の上映会「彫る～棟方志功の世界」',place:'苫小牧市美術博物館 研修室',tag:'上映会・無料',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/munakata.html'},
{date:'9/23(水・祝)',time:'10:00〜',title:'ベビープラネタリウム',place:'苫小牧市科学センター',tag:'親子・無料',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/25(金)',time:'18:30〜20:00',title:'星空観望会「中秋の名月の観望と撮影会」',place:'苫小牧市科学センター',tag:'天文・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/26(土)',time:'10:00〜12:30',title:'公園の「なぜ？」を見つけ隊！',place:'出光カルチャーパーク・中央図書館',tag:'自然・子ども',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/26(土)',time:'14:30〜15:15',title:'ミール科学あそび「紙飛行機を作ろう」',place:'苫小牧市科学センター',tag:'科学・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'9/26(土)',time:'14:00〜15:30',title:'美術博物館大学講座「北海道のアートプロジェクトと彫刻公園」',place:'苫小牧市美術博物館',tag:'講座',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/daigaku2026.html'},
{date:'9/26(土)',time:'時間は公式ページ確認',title:'パラスポーツ体験教室（ボッチャ）',place:'苫小牧市内スポーツ施設',tag:'スポーツ',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/26(土)',time:'時間は公式ページ確認',title:'ウォーキングフェスティバル（駅前まちなかオレンジウォークコース）',place:'苫小牧駅前・まちなか',tag:'健康・スポーツ',url:'https://www.city.tomakomai.hokkaido.jp/calendar/'},
{date:'9/26(土)',time:'時間は公式ページ確認',title:'ハルナギFES2026',place:'苫小牧市文化交流センター',tag:'音楽・地域',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'9/30(水)',time:'10:00〜',title:'ベビープラネタリウム',place:'苫小牧市科学センター',tag:'親子・無料',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/R0809.html'},
{date:'10/3(土)',time:'10:00〜12:00',title:'科学ふれあい教室「回転の科学！フシギなコマを作ろう」',place:'苫小牧市科学センター',tag:'科学・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'10/3(土)',time:'13:30〜16:50',title:'市民交流将棋大会',place:'苫小牧市民文化ホール ART CUBES ルーム5',tag:'文化・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/eventannai/siminbunkasai.html'},
{date:'10/3(土)〜10/4(日)',time:'時間は公式ページ確認',title:'市民文化祭 総合展示発表',place:'苫小牧市民文化ホール ART CUBES',tag:'市民文化祭',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/eventannai/siminbunkasai.html'},
{date:'10/5(月)',time:'9:00〜15:00',title:'勇払地区文化祭',place:'勇払公民館',tag:'地域・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/eventannai/siminbunkasai.html'},
{date:'10/10(土)',time:'14:00〜15:30',title:'ギャラリートーク＋ワークショップ「裏彩色体験」',place:'苫小牧市美術博物館',tag:'美術・体験',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/munakata.html'},
{date:'10/18(日)',time:'12:00〜16:00',title:'市民川柳大会',place:'苫小牧市立中央図書館 2階講堂',tag:'文化・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/eventannai/siminbunkasai.html'},
{date:'10/24(土)',time:'14:00〜15:30',title:'美術博物館大学講座「サケの生態と水族館の仕事」',place:'苫小牧市美術博物館',tag:'講座',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/daigaku2026.html'},
{date:'10/25(日)',time:'10:00〜12:00／13:30〜15:30',title:'わくわくさんすう教室',place:'苫小牧市科学センター',tag:'子ども・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'10/25(日)',time:'14:00〜16:00',title:'苫小牧市主催 婚活パーティー',place:'苫小牧市民文化ホール ART CUBES アートスペース',tag:'交流',url:'https://www.city.tomakomai.hokkaido.jp/shisei/shisei/shiseihoshin/sonohoka/tomakon.html'},
{date:'10/31(土)',time:'10:30〜11:30',title:'宇宙ステーション「ミール」ガイド「コックピットとトイレのひみつ」',place:'苫小牧市科学センター',tag:'科学・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'10/31(土)',time:'11:00〜11:30／13:30〜14:00',title:'担当学芸員によるギャラリートーク',place:'苫小牧市美術博物館',tag:'美術・解説',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/munakata.html'},
{date:'11/3(火・祝)',time:'10:00〜12:00',title:'文化の日工作教室「七宝焼きを作ろう」',place:'苫小牧市科学センター',tag:'科学・工作',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'11/3(火・祝)',time:'10:00／11:30／13:30／15:00（各回約30分）',title:'地層標本 展示説明会',place:'苫小牧市美術博物館 第一収蔵展示室',tag:'博物館・無料',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/tisou.html'},
{date:'11/7(土)',time:'9:30〜11:00／13:30〜15:00',title:'プレスクール工作体験「クリスマスツリーのキーホルダーをつくろう」',place:'苫小牧市科学センター',tag:'未就学児・工作',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'11/7(土)',time:'14:00〜15:30',title:'美術博物館大学講座「恵庭市出土の7〜9世紀の金属製品について」',place:'苫小牧市美術博物館',tag:'講座',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/daigaku2026.html'},
{date:'11/8(日)',time:'10:00〜11:30',title:'地層標本の作成体験',place:'苫小牧市美術博物館',tag:'体験・無料',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/tisou.html'},
{date:'11/10(火)',time:'時間は公式ページ確認',title:'ルーランド・デュイ チェロリサイタル',place:'苫小牧信用金庫本店2階 市民サロン',tag:'音楽・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'11/15(日)',time:'10:00〜11:00／13:00〜14:00',title:'食育・科学教室「“なるほど”がいっぱい！みるく教室」',place:'苫小牧市科学センター',tag:'食育・科学',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'11/15(日)',time:'11:00開場／11:50開演／13:20終演予定',title:'NHKのど自慢',place:'苫小牧市民文化ホール ART CUBES',tag:'音楽・公開番組',url:'https://www.city.tomakomai.hokkaido.jp/shisei/sonota/shiminhoru/nodojiman.html'},
{date:'11/20(金)',time:'18:00〜18:40',title:'夜の上映会「彫る～棟方志功の世界」',place:'苫小牧市美術博物館 研修室',tag:'上映会・無料',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/munakata.html'},
{date:'11/20(金)',time:'時間は公式ページ確認',title:'夜会シリーズ vol.14',place:'苫小牧信用金庫本店2階 市民サロン',tag:'音楽・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'11/23(月・祝)',time:'16:10〜16:50／17:10〜17:50',title:'全国一斉 熟睡プラ寝たリウム',place:'苫小牧市科学センター',tag:'プラネタリウム',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'11/28(土)',time:'10:00〜12:00／13:30〜15:30',title:'木工教室「本立てを作ろう」',place:'苫小牧市科学センター',tag:'工作・子ども',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'11/28(土)',time:'時間は公式ページ確認',title:'縄文時代に関する講演会',place:'ホテルウイングインターナショナル苫小牧',tag:'講演・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'12/6(日)',time:'10:00〜12:00',title:'電子工作教室「FMマイクを作ろう」',place:'苫小牧市科学センター',tag:'電子工作',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'12/12(土)',time:'14:00〜15:30',title:'美術博物館大学講座「南と北の16世紀 戦国時代の肥後を中心に」',place:'苫小牧市美術博物館',tag:'講座',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/daigaku2026.html'},
{date:'12/19(土)',time:'10:00〜11:30',title:'天文教室「星座早見盤を作ろう」',place:'苫小牧市科学センター',tag:'天文・工作',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'12/19(土)〜2027/3/7(日)',time:'9:30〜17:00',title:'企画展「まちの楽しみ」',place:'苫小牧市美術博物館',tag:'展示',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/2026.html'},
{date:'12/19(土)〜2027/3/7(日)',time:'9:30〜17:00',title:'企画展「綴る絵―川上澄生と能登正智の版画絵本」',place:'苫小牧市美術博物館',tag:'展示',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/tenrankai/2026.html'},
{date:'2027/1/6(水)',time:'10:00〜12:00／13:30〜15:30',title:'冬休み木工教室「ひつじのパズルを作ろう」',place:'苫小牧市科学センター',tag:'工作・子ども',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/1/7(木)',time:'10:00〜12:00／13:30〜15:30',title:'こども環境工作教室「ソーラーカーを作ろう」',place:'苫小牧市科学センター',tag:'環境・工作',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/1/8(金)',time:'詳細は公式発表待ち',title:'夜間開館科学工作教室',place:'苫小牧市科学センター',tag:'科学・夜間',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/1/9(土)',time:'14:30〜15:15',title:'ミール科学あそび「スーパーボールロケットを作ろう」',place:'苫小牧市科学センター',tag:'科学・工作',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/1/9(土)',time:'14:00〜15:30',title:'美術博物館大学講座「浦島太郎はおめでたい～三長命をめぐる浦島伝説」',place:'苫小牧市美術博物館',tag:'講座',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/daigaku2026.html'},
{date:'2027/1〜3月（予定）',time:'日時詳細は公式発表待ち',title:'OrgofA「異邦人の庭」',place:'旧すえくに医院',tag:'舞台・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'2027/1/31(日)',time:'時間は公式ページ確認',title:'向井バレエシアター45周年＆向井美賀子追悼公演',place:'苫小牧市民文化ホール ART CUBES',tag:'舞台',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'2027/2/6(土)',time:'10:00〜12:00',title:'科学ふれあい教室',place:'苫小牧市科学センター',tag:'科学・子ども',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/2/13(土)',time:'10:00〜12:00',title:'プログラミング教室「パソコンでプログラミング体験」',place:'苫小牧市科学センター',tag:'プログラミング',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/2/20(土)',time:'14:00〜15:30',title:'美術博物館大学講座「身近な『文字』を楽しむ」・卒業式',place:'苫小牧市美術博物館',tag:'講座',url:'https://www.city.tomakomai.hokkaido.jp/hakubutsukan/gyoji/daigaku2026.html'},
{date:'2027/2/27(土)',time:'時間は公式ページ確認',title:'アール・ブリュット in 苫小牧 2027',place:'苫小牧市文化交流センター',tag:'アート',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'2027/3/6(土)',time:'10:00〜12:00',title:'科学ふれあい教室「色！いろいろ！？イロのひみつ」',place:'苫小牧市科学センター',tag:'科学・体験',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/3/20(土)〜3/24(水)',time:'時間は公式ページ確認',title:'第3回 U-20 若者美術展',place:'苫小牧市美術博物館',tag:'美術・若者',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'2027/3/20(土)',time:'10:30〜11:30',title:'ミールガイド「クバントの中に入ってみよう」',place:'苫小牧市科学センター',tag:'宇宙・見学',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/3/22(月)',time:'時間は公式ページ確認',title:'苫小牧ウインド・アンサンブル創団40周年記念演奏会',place:'苫小牧市民文化ホール ART CUBES',tag:'音楽',url:'https://www.city.tomakomai.hokkaido.jp/kyoiku/shogaigakushu/bunka/bunkageijutsu/shinkojoseijigyo/jigyoitiran.html'},
{date:'2027/3/25(木)',time:'18:30〜20:00',title:'星空観望会「天文台で木星の観望と撮影会」',place:'苫小牧市科学センター',tag:'天文・小規模',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'},
{date:'2027/3/26(金)',time:'10:00〜12:00／13:30〜15:30',title:'春休み木工教室「ティッシュボックスを作ろう」',place:'苫小牧市科学センター',tag:'工作・子ども',url:'https://www.city.tomakomai.hokkaido.jp/kagaku/event/school/r8list_m.html'}
];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderEvents(){const cal=document.getElementById('cal');if(!cal||cal.classList.contains('hidden'))return;if(cal.querySelector('#tomakomaiEventList'))return;const box=document.createElement('div');box.id='tomakomaiEventList';box.className='card';box.style.marginTop='14px';box.innerHTML=`<div style="display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:10px"><div><div class="title" style="font-size:19px">🎪 苫小牧イベント情報</div><div class="meta">地域行事・教室・展示・講座・体験会まで掲載／公式情報を随時更新</div></div><span class="pill">${EVENTS.length}件</span></div><div style="display:grid;gap:9px">${EVENTS.map(e=>`<a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer" style="display:block;text-decoration:none;color:inherit;border:1px solid #dbe8ef;border-radius:12px;padding:12px;background:#fff"><div style="display:flex;justify-content:space-between;gap:8px;align-items:flex-start"><strong style="font-size:15px;line-height:1.4">${esc(e.title)}</strong><span class="pill" style="white-space:nowrap">${esc(e.tag)}</span></div><div style="margin-top:7px;font-weight:800;color:#0b76a8">📅 ${esc(e.date)}　⏰ ${esc(e.time)}</div><div class="meta" style="margin-top:5px">📍 ${esc(e.place)}　› 公式情報</div></a>`).join('')}</div><a class="btn" href="https://www.city.tomakomai.hokkaido.jp/calendar/" target="_blank" rel="noopener noreferrer" style="display:block;text-align:center;margin-top:12px;text-decoration:none">苫小牧市 行事カレンダーを確認</a>`;cal.appendChild(box);}
const observer=new MutationObserver(()=>setTimeout(renderEvents,0));observer.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',()=>setTimeout(renderEvents,0));window.addEventListener('load',()=>setTimeout(renderEvents,300));
})();